version: '3.8'

services:
  web: 
    container_name: 'web'
    build: .
    env_file:
    - .env
    ports:
      - "4000:4000"
    command: go run .
  db: 
    container_name: 'db'
    image: postgres:alpine
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_SSLMODE=${DB_SSLMODE}
      - POSTGRES_TIMEZONE=${DB_TIMEZONE}
    ports:
      - "5432:5432"
    volumes:
      - pgdb:/var/lib/postgresql/data
volumes:
  pgdb: 